### ISSUE TITLE
'case' and 'remove-if-not' not supported in Emacs 26.3

### ISSUE THREAD

**Issue by mbutz** [derekxkwan/company-tidal-backend#1]
Hi,

thanks a lot for providing a `company` package for Tidal! This is especially helpful for me as a beginner. To get it running on Emacs 26.3 (doom) I had to make to changes in `company-tidal-backend`:

```
(defun company-tidal-backend (command &optional arg &rest ignored)
   (interactive (list 'interactive))

   (cl-case command ;; old -----> case
     (interactive (company-begin-backend 'company-tidal-backend))
     (prefix (and (eq major-mode 'tidal-mode)
                 (company-grab-symbol)))
     (candidates
     (cl-remove-if-not ;; old ----> remove-if-not
       (lambda (c) (string-prefix-p arg c))
       (append tidal-sample-completions tidal-lang-completions
    	       tidal-synth-completions tidal-fx-completions
	       )
        )))
   )
```
My internal knowledge of Emacs and Lisp is very limited. So this was just based on trial and error.

Hope that helps.

**Comment by derekxkwan** [comment]
ah cool thx! i actually switched from emacs to vim (easier defaults on the hands) so i kinda don't use this anymore and also my knowledge of company was extremely limited as well so i don't really plan on revisiting this code (mb i should just archive the repo) but feel free to fork and continue on!
